<#
.SYNOPSIS
    Setup Windows PulseAudio for WSL Audio Support

.DESCRIPTION
    This script sets up PulseAudio on Windows to enable audio in WSL.
    Run this script in Windows PowerShell (not in WSL).

.NOTES
    Run as Administrator for best results
#>

[CmdletBinding()]
param()

Write-Host ""
Write-Host "🔊 Windows PulseAudio Setup for WSL" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""

# Check if running in Windows
if ($env:WSL_DISTRO_NAME) {
    Write-Host "❌ Error: This script must be run in Windows PowerShell, not in WSL!" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please:" -ForegroundColor Yellow
    Write-Host "  1. Open Windows PowerShell" -ForegroundColor Yellow
    Write-Host "  2. Navigate to the project directory (Windows path)" -ForegroundColor Yellow
    Write-Host "  3. Run: .\scripts\setup_windows_audio_for_wsl.ps1" -ForegroundColor Yellow
    exit 1
}

Write-Host "✓ Running in Windows PowerShell" -ForegroundColor Green
Write-Host ""

# Check if PulseAudio is installed
$pulseAudioPath = "C:\PulseAudio"
$pulseAudioBin = Join-Path $pulseAudioPath "bin\pulseaudio.exe"

if (Test-Path $pulseAudioBin) {
    Write-Host "✓ PulseAudio is already installed at: $pulseAudioPath" -ForegroundColor Green
} else {
    Write-Host "📦 Installing PulseAudio..." -ForegroundColor Yellow
    Write-Host ""

    # Try to install via winget
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        Write-Host "Installing via winget..."
        try {
            winget install --id=PulseAudio.PulseAudio -e --silent
            Write-Host "✓ PulseAudio installed successfully" -ForegroundColor Green
        }
        catch {
            Write-Host "⚠ Winget installation failed" -ForegroundColor Yellow
        }
    }

    # Check again if installed
    if (-not (Test-Path $pulseAudioBin)) {
        Write-Host ""
        Write-Host "⚠ PulseAudio not found. Manual installation needed:" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Option 1: Install via winget" -ForegroundColor Cyan
        Write-Host "  winget install --id=PulseAudio.PulseAudio -e" -ForegroundColor White
        Write-Host ""
        Write-Host "Option 2: Download manually" -ForegroundColor Cyan
        Write-Host "  1. Visit: https://www.freedesktop.org/wiki/Software/PulseAudio/Ports/Windows/Support/" -ForegroundColor White
        Write-Host "  2. Download pulseaudio-X.X.zip" -ForegroundColor White
        Write-Host "  3. Extract to C:\PulseAudio" -ForegroundColor White
        Write-Host ""
        Write-Host "Then run this script again." -ForegroundColor Yellow
        exit 1
    }
}

Write-Host ""

# Create configuration directory
$configDir = Join-Path $pulseAudioPath "etc\pulse"
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
    Write-Host "✓ Created configuration directory: $configDir" -ForegroundColor Green
}

# Create configuration file
$configFile = Join-Path $configDir "default.pa"
Write-Host "📝 Creating PulseAudio configuration..." -ForegroundColor Yellow

$configContent = @"
# PulseAudio Configuration for WSL
# Generated by setup_windows_audio_for_wsl.ps1

# Load TCP module to allow WSL connections
load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;172.16.0.0/12

# Load esound protocol for compatibility
load-module module-esound-protocol-tcp auth-ip-acl=127.0.0.0/8

# Windows audio output
load-module module-waveout sink_name=output source_name=input record=0

# Optional: Load additional modules
# load-module module-detect
"@

$configContent | Out-File -FilePath $configFile -Encoding UTF8 -Force
Write-Host "✓ Configuration created: $configFile" -ForegroundColor Green
Write-Host ""

# Check if PulseAudio is running
$pulseProcess = Get-Process -Name pulseaudio -ErrorAction SilentlyContinue

if ($pulseProcess) {
    Write-Host "⚠ PulseAudio is already running (PID: $($pulseProcess.Id))" -ForegroundColor Yellow
    Write-Host ""
    $restart = Read-Host "Restart PulseAudio to apply new configuration? (y/N)"

    if ($restart -eq 'y' -or $restart -eq 'Y') {
        Write-Host "Stopping PulseAudio..."
        Stop-Process -Name pulseaudio -Force
        Start-Sleep -Seconds 2
    } else {
        Write-Host "⚠ Configuration changes will take effect after restart" -ForegroundColor Yellow
    }
}

# Start PulseAudio
if (-not (Get-Process -Name pulseaudio -ErrorAction SilentlyContinue)) {
    Write-Host "🚀 Starting PulseAudio..." -ForegroundColor Cyan
    Start-Process -FilePath $pulseAudioBin -WindowStyle Hidden
    Start-Sleep -Seconds 2

    if (Get-Process -Name pulseaudio -ErrorAction SilentlyContinue) {
        Write-Host "✓ PulseAudio is running" -ForegroundColor Green
    } else {
        Write-Host "⚠ Failed to start PulseAudio automatically" -ForegroundColor Yellow
        Write-Host "Start manually: cd C:\PulseAudio\bin; .\pulseaudio.exe" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "✅ Windows Setup Complete!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""
Write-Host "📋 NEXT STEPS - In WSL:" -ForegroundColor Cyan
Write-Host ""
Write-Host "  1. Open your WSL terminal" -ForegroundColor White
Write-Host "  2. Run: ./scripts/fix_wsl_audio.sh" -ForegroundColor Yellow
Write-Host "  3. Restart your WSL terminal" -ForegroundColor White
Write-Host "  4. Test: ./dev.sh run --speak `"Testing audio`"" -ForegroundColor Yellow
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""
Write-Host "🔧 MANAGEMENT:" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Check if running:" -ForegroundColor White
Write-Host "    Get-Process pulseaudio" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Stop PulseAudio:" -ForegroundColor White
Write-Host "    Stop-Process -Name pulseaudio" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Start PulseAudio:" -ForegroundColor White
Write-Host "    cd C:\PulseAudio\bin; .\pulseaudio.exe" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Start at Windows boot (optional):" -ForegroundColor White
Write-Host "    Create shortcut in: shell:startup" -ForegroundColor Yellow
Write-Host "    Target: C:\PulseAudio\bin\pulseaudio.exe" -ForegroundColor Yellow
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""
Write-Host "💡 ALTERNATIVE - Easier Option:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Just run Liquid ASCII directly in Windows PowerShell:" -ForegroundColor White
Write-Host "    .\scripts\dev.ps1 run --speak `"This works without WSL!`"" -ForegroundColor Yellow
Write-Host ""
